version: "3"

services:
  app-db-dev:
    image: mongo:latest
    container_name: app-db-dev
    ports:
      - "27017:27017"
    expose:
      - "27017"

  app-service-dev:
    container_name: app-service-dev
    build:
      context: ./
      dockerfile: Dockerfile-dev
    command: npm run dev
    depends_on:
      - app-db-dev
    volumes:
      - "./:/usr/src/app"
      - "./package.json:/usr/src/package.json"
    ports:
      - "8000:8000"
    environment:
      MONGO_URL: "mongodb://app-db-dev:27017/SampleDB"
      MONGO_URL_TEST: "mongodb://app-db-dev:27017/SampleDB"
      SESSION_SECRET: "xxxxxxx"
